theme:
  
  version: 1.0
  author: linotype

  name: Default
  desc: default theme

  map:
    
    home:
      name: Home
      desc: The home page
      icon: '@Linotype/Icons/home.svg'
      public: true
      path: /
      template: Home
      type: page
      view: true
      edit: true
      delete: false
      create: false

    about:
      name: About
      desc: Present yourself
      icon: '@Linotype/Icons/user.svg'
      public: true
      path: /about
      template: About
      type: page
      view: true
      edit: true
      delete: false
      create: false

    articles:
      name: Articles
      desc: List of article
      icon: '@Linotype/Icons/book.svg'
      public: true
      path: /articles
      template: Articles
      type: page
      view: true
      edit: true
      delete: false
      create: false

    article:
      name: Article
      desc: Display one article
      icon: '@Linotype/Icons/bookmark.svg'
      public: true
      path: /article/{id}
      template: Article
      type: post
      view: true
      edit: true
      delete: false
      create: false

    contact:
      name: Contact
      desc: Contact form
      icon: '@Linotype/Icons/send.svg'
      public: true
      path: /contact
      template: Form
      type: page
      view: true
      edit: true
      delete: false
      create: false
      override:
        form:
          override:
            form_id: contact
    
    test:
      name: Test
      desc: Simple test page
      icon: '@Linotype/Icons/alert-circle.svg'
      public: false
      path: /test
      template: Test
      type: page
      view: true
      edit: true
      delete: false
      create: false

    composer:
      name: Composer
      desc: Simple test page for composer
      icon: '@Linotype/Icons/file-plus.svg'
      public: false
      path: /composer
      template: Composer
      type: page
      view: true
      edit: true
      delete: false
      create: false
